export const API_ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  FIELD_ALREADY_EXISTS: "FIELD_ALREADY_EXISTS",
  BAD_CREDENTIALS: "BAD_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  RATE_LIMIT: "RATE_LIMIT",
  FORBIDDEN: "FORBIDDEN",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  MESSAGE_NOT_READABLE: "MESSAGE_NOT_READABLE",
  ARGUMENT_TYPE_MISMATCH: "ARGUMENT_TYPE_MISMATCH",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DEPENDENCY_UNAVAILABLE: "DEPENDENCY_UNAVAILABLE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  USER_BANNED: "USER_BANNED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE"
} as const;


